version: "3.8"

services:
  bank_simulator:
    container_name: bank_simulator
    image: bbyars/mountebank:2.8.1
    ports:
      - "2525:2525"
      - "8080:8080"
    command: --configfile /imposters/bank_simulator.ejs
    volumes:
      - type: bind
        source: ./imposters
        target: /imposters
  
  payment-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BankUrl=http://bank_simulator:8080
    depends_on:
      - bank_simulator